<?php

$transactions = [
    [
        "id" => 1,
        "date" => "2019-01-01",
        "amount" => 100.00,
        "description" => "Payment for groceries",
        "merchant" => "SuperMart",
    ],
    [
        "id" => 2,
        "date" => "2020-02-15",
        "amount" => 75.50,
        "description" => "Dinner with friends",
        "merchant" => "Local Restaurant",
    ],
    [
        "id" => 3,
        "date" => "2021-03-10",
        "amount" => 200.00,
        "description" => "New phone purchase",
        "merchant" => "Tech Store",
    ],
    [
        "id" => 4,
        "date" => "2022-04-05",
        "amount" => 50.75,
        "description" => "Gas station refill",
        "merchant" => "Fuel Express",
    ],
    [
        "id" => 5,
        "date" => "2023-05-20",
        "amount" => 30.00,
        "description" => "Book purchase",
        "merchant" => "City Bookstore",
    ],
    [
        "id" => 6,
        "date" => "2020-06-15",
        "amount" => 120.90,
        "description" => "New shoes",
        "merchant" => "Fashion Outlet",
    ],
    [
        "id" => 7,
        "date" => "2019-07-22",
        "amount" => 45.60,
        "description" => "Coffee and snacks",
        "merchant" => "Cafe Deluxe",
    ],
    [
        "id" => 8,
        "date" => "2021-08-30",
        "amount" => 89.99,
        "description" => "Online course",
        "merchant" => "EduPlatform",
    ],
    [
        "id" => 9,
        "date" => "2022-09-12",
        "amount" => 15.25,
        "description" => "Movie ticket",
        "merchant" => "Cinema World",
    ],
    [
        "id" => 10,
        "date" => "2023-10-08",
        "amount" => 300.00,
        "description" => "Hotel stay",
        "merchant" => "Grand Hotel",
    ],
    [
        "id" => 11,
        "date" => "2019-11-25",
        "amount" => 20.00,
        "description" => "Gym membership",
        "merchant" => "Fit Center",
    ],
    [
        "id" => 12,
        "date" => "2020-12-18",
        "amount" => 65.40,
        "description" => "Grocery shopping",
        "merchant" => "SuperMart",
    ],
    [
        "id" => 13,
        "date" => "2021-01-05",
        "amount" => 99.99,
        "description" => "Wireless headphones",
        "merchant" => "Tech Store",
    ],
    [
        "id" => 14,
        "date" => "2022-02-14",
        "amount" => 150.00,
        "description" => "Valentine's dinner",
        "merchant" => "Romantic Bistro",
    ],
    [
        "id" => 15,
        "date" => "2023-03-21",
        "amount" => 400.00,
        "description" => "Furniture purchase",
        "merchant" => "Home Decor",
    ],
    [
        "id" => 16,
        "date" => "2019-04-10",
        "amount" => 27.50,
        "description" => "Online subscription",
        "merchant" => "StreamFlix",
    ],
    [
        "id" => 17,
        "date" => "2020-05-19",
        "amount" => 10.99,
        "description" => "Music streaming service",
        "merchant" => "TuneWorld",
    ]
];
